---
- name: Download and install latest WordPress
  command: wp core download --path=/vagrant/wordpress --locale=en_US --version=latest
  become: true
  become_method: sudo
  become_user: www-data
  ignore_errors: true

- name: Set WordPress permissions
  file:
    path: /vagrant/wordpress
    owner: www-data
    group: www-data
    mode: 0755
    recurse: yes
    state: directory

- name: Symlink installed WordPress into web root
  file:
    src: /vagrant/wordpress
    path: /var/www/wordpress
    state: link

- name: Create database for WordPress
  mysql_db:
    name: wordpress
    state: present
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci

- name: Create WordPress MySQL user
  mysql_user:
    name: "{{ wp_db_user_name }}"
    password: "{{ wp_db_user_password }}"
    state: present
    priv: "wordpress.*:ALL"
    update_password: always
    
- name: Generate wp-config.php
  shell: wp config create --dbname=wordpress --dbuser={{ wp_db_user_name }} --dbpass={{ wp_db_user_password }} --dbcharset=utf8mb4 --dbcollate=utf8mb4_unicode_ci --locale=en_US --extra-php --force
  become: true
  become_method: sudo
  become_user: www-data
  args:
    chdir: /vagrant/wordpress
    stdin: |
      define( 'WP_DEBUG', {{ wp_debug_value }} );
      define( 'SAVEQUERIES', true );
